#http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
#http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

#### Application Port설정
server:
  port: 8080
  servlet:    context-path: /sample
---
#### Spring Boot Default Error Page
server:  error:    whitelabel:      enabled: false
---
#### CharacterEncodingFilter
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profiles:
    active: local # 기본 환경 선택 # local 환경
  devtools:    livereload:      enabled: true    restart:      exclude: /static/**,/templates/**
---
spring:
  datasource:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@10.2.31.107:1521:wodb1
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@10.2.31.107:1521:wodb1
    username: srsystem
    password: alfresco
    initialization-mode: always    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
---
#### Custom Variable
sso:
  protocol: https
  url: gw.uwiseone.net
  port: 443
  api-secret: SmartRunner4
  
  

 